apiVersion: ray.io/v1
kind: RayService
metadata:
  name: image-caption-service
spec:
  serveConfigV2: |
    applications:
      - name: hello
        import_path: ray.serve.examples.hello_world:app
        route_prefix: /hello
  # serveConfigV2: |
  #   applications:
  #     - name: caption_app
  #       import_path: caption_service:app
  #       route_prefix: /caption
  #       runtime_env:
  #         working_dir: "https://raw.githubusercontent.com/CatFish47/RayServiceImageCaption/main/image-caption-serve.zip"
  #         pip:
  #           - transformers
  #           - torch
  #           - torchvision
  #           - fastapi
  #           - requests
  rayClusterConfig:
    rayVersion: "2.41.0"
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.41.0-py39-aarch64
              resources:
                requests:
                  cpu: 2
                  memory: 3Gi
                limits:
                  cpu: 2
                  memory: 3Gi
              ports:
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - groupName: worker-group
        replicas: 1
        minReplicas: 1
        maxReplicas: 3
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: rayproject/ray:2.41.0-py39-aarch64
                resources:
                  requests:
                    cpu: 1
                    memory: 3Gi
                  limits:
                    cpu: 2
                    memory: 3Gi
                # readinessProbe:
                #   exec:
                #     command: ["/bin/bash", "-c", "exit 0"]
                #   initialDelaySeconds: 20
                #   periodSeconds: 10
                #   failureThreshold: 60
